# Generated by Django 4.2.9 on 2026-06-10 21:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0003_parkinglot_last_occupancy_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_slots', models.IntegerField(default=0)),
                ('occupied_slots', models.IntegerField(default=0)),
                ('available_slots', models.IntegerField(default=0)),
                ('occupancy_rate', models.FloatField(default=0.0)),
                ('slot_states', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('edge_ai', 'Edge AI Service'), ('manual', 'Manual Override'), ('simulation', 'Simulation')], default='edge_ai', max_length=20)),
                ('edge_timestamp', models.DateTimeField(help_text='Timestamp from the edge service payload')),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('parking_lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_snapshot', to='parking.parkinglot')),
            ],
            options={
                'verbose_name': 'Occupancy Snapshot',
                'verbose_name_plural': 'Occupancy Snapshots',
            },
        ),
        migrations.CreateModel(
            name='OccupancyHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_slots', models.IntegerField()),
                ('occupied_slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('occupancy_rate', models.FloatField()),
                ('recorded_at', models.DateTimeField(help_text='Timestamp reported by the edge service')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_history', to='parking.parkinglot')),
            ],
            options={
                'verbose_name': 'Occupancy History',
                'verbose_name_plural': 'Occupancy History',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['parking_lot', '-recorded_at'], name='occupancy_o_parking_06add1_idx')],
            },
        ),
    ]
