# Generated by Django 4.2.9 on 2026-06-09 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occupancylog',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_logs', to='parking.parkingslot'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('lot', 'slot_number')},
        ),
        migrations.AlterUniqueTogether(
            name='parkingschedule',
            unique_together={('lot', 'day_of_week')},
        ),
    ]
