# Generated by Django 4.2.9 on 2026-06-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='last_occupancy_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='occupancy_rate_cache',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='occupied_slots_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='total_slots_cache',
            field=models.IntegerField(default=0),
        ),
    ]
